name: swiyu

options:
  developmentLanguage: en
  deploymentTarget: [iOS]
  generateEmptyDirectories: true
  
configs:
  Dev (debug): debug
  Dev (release): release
  Test (debug): debug
  Test (release): release
  Ref (debug): debug
  Ref (release): release
  Abn (debug): debug
  Abn (release): release
  Abn Store (debug): debug
  Abn Store (release): release
  Prod (debug): debug
  Prod (release): release

fileGroups: [
  "../Projects",
  "../../Modules",
  "../../Makefile"
]
